---
name: coords
version: 1.1.0
author: BbugsCO
main: showCoords\showCoords
src-namespace-prefix: showCoords
description: Display Coordinates
api: [4.0.0]
mcpe-protocol:
- 475
load: STARTUP
commands:
  coords:
    description: Show your coordinates
    permission: coords
    usage: /coords [on/off]
permissions:
  coords:
    default: op
    description: perm to use coords
...
