---
name: coords
version: 1.0.0
author: BbugsCO
main: BbugsCO\coords\showCoords
description: Display Coordinates
api:
- 3.0.0
mcpe-protocol:
- 448
commands:
  coords:
    description: Show your coordinates
    permission: coords
    usage: /coords
permissions:
  coords.command:
    default: op
    description: perm to use coords
...
